name: caco2-3D
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=3.3.8
  - asttokens=3.0.0
  - async-lru=2.0.4
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - autopep8=2.0.4
  - babel=2.16.0
  - backports.tarfile=1.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.10.0
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=4.0.0
  - click=8.1.8
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - cookiecutter=2.6.0
  - cryptography=44.0.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dftd4=3.7.0
  - diff-match-patch=20200713
  - dill=0.3.8
  - docstring-to-markdown=0.11
  - docutils=0.21.2
  - executing=0.8.3
  - flake8=7.1.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - inflection=0.5.1
  - intel-openmp=2024.2.1
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - isort=6.0.1
  - jaraco.classes=3.2.1
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyring=25.6.0
  - krb5=1.20.1
  - libblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mctc-lib=0.3.2
  - mdurl=0.1.0
  - mistune=3.1.2
  - mkl=2024.2.2
  - more-itertools=10.3.0
  - multicharge=0.3.0
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numpydoc=1.7.0
  - openssl=3.1.0
  - overrides=7.4.0
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.10.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pylint=3.3.5
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-slugify=5.0.2
  - pytoolconfig=1.2.6
  - pyuca=1.2
  - pywin32=308
  - pywin32-ctypes=0.2.2
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - roman-numerals-py=3.1.0
  - rope=1.13.0
  - rpds-py=0.22.3
  - rtree=1.0.1
  - send2trash=1.8.2
  - setuptools=78.1.1
  - simple-dftd3=1.2.1
  - sip=6.7.12
  - six=1.17.0
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spyder=6.0.5
  - spyder-kernels=3.0.3
  - sqlite=3.45.3
  - stack_data=0.2.0
  - superqt=0.7.3
  - tabulate=0.9.0
  - tbb=2021.7.0
  - tblite=0.4.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - toml-f=0.4.2
  - tomli=2.0.1
  - tomlkit=0.13.2
  - tornado=6.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unidecode=1.3.8
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - watchdog=4.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - whatthepatch=1.0.2
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.17.0
  - xtb=6.7.1
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.40.2
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.7.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.0
      - aiosignal==1.3.2
      - alembic==1.16.4
      - attrs==25.3.0
      - charset-normalizer==3.4.2
      - colorlog==6.9.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.1.1
      - datasets==3.6.0
      - deepchem==2.8.0
      - filelock==3.18.0
      - fonttools==4.59.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - greenlet==3.2.3
      - huggingface-hub==0.32.0
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lightgbm==4.6.0
      - llvmlite==0.44.0
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - optuna==4.2.1
      - packaging==25.0
      - pandas==1.5.3
      - pillow==11.0.0
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytz==2025.2
      - rdkit==2025.3.2
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - shap==0.47.2
      - slicer==0.0.8
      - sqlalchemy==2.0.42
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tokenizers==0.19.1
      - torch==2.8.0.dev20250524+cu128
      - torch-geometric==2.6.1
      - torchaudio==2.6.0.dev20250525+cu128
      - torchvision==0.22.0.dev20250525+cu128
      - tqdm==4.67.1
      - transformers==4.40.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - unimol-tools==0.1.2.post2
      - urllib3==2.4.0
      - xxhash==3.5.0
      - yarl==1.20.0
