name: mordred
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alabaster=0.7.16
  - arrow=1.3.0
  - astroid=3.3.8
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.3.0
  - autopep8=2.0.4
  - babel=2.16.0
  - backcall=0.2.0
  - backports.tarfile=1.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.10.0
  - blas=1.0
  - bleach=6.2.0
  - boost=1.78.0
  - boost-cpp=1.78.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.1
  - cookiecutter=2.6.0
  - cryptography=44.0.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - diff-match-patch=20200713
  - dill=0.3.8
  - docstring-to-markdown=0.11
  - docutils=0.21.2
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - flake8=7.1.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - greenlet=3.1.1
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - inflection=0.5.1
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - isort=6.0.1
  - jaraco.classes=3.2.1
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.3.0
  - keyring=25.6.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mordred=1.2.0
  - more-itertools=10.3.0
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.10.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - propcache=0.3.1
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycairo=1.23.0
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pylint=3.3.5
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-slugify=5.0.2
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytoolconfig=1.2.6
  - pytz=2024.1
  - pyuca=1.2
  - pywin32=308
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - rdkit=2023.03.1
  - referencing=0.30.2
  - reportlab=3.5.67
  - requests=2.32.3
  - rich=13.9.4
  - rope=1.13.0
  - rpds-py=0.22.3
  - rtree=1.0.1
  - setuptools=78.1.1
  - sip=6.7.12
  - six=1.17.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spyder=6.0.5
  - spyder-kernels=3.0.3
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - stack_data=0.2.0
  - superqt=0.7.3
  - tabulate=0.9.0
  - tbb=2021.8.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tomli=2.0.1
  - tomlkit=0.13.2
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.20348.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - watchdog=4.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.40.2
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
